// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaevvlkxfhxepttbchas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZXZ2bGt4Zmh4ZXB0dGJjaGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDgwNzMsImV4cCI6MjA3MjI4NDA3M30.9vY2bvMj3e3CAt3Udfx9oNzdo0RC1pDGxqT6gFoZIKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});